Vega Custom Toolbar
bcdev/chartlets pull request #23
Opened 2024-10-28 14:59 UTC by b-yogesh

2024-11-05 12:59 UTC, forman requested changes

2024-11-05 12:59 UTC, forman commented on dashi/src/lib/components/DashiDropdown.tsx
> +  panelIndex: number;
The term `panel` does not exist is the API, the `lib` part. This is relevant fort the demo only.

Also, I don't see why this is needed in every component now.

2025-03-13 14:32 UTC, forman commented
@b-yogesh I close this PR, I create an issue instead that specifies what is needed.

2025-03-13 14:38 UTC, b-yogesh commented
> @b-yogesh I close this PR, I create an issue instead that specifies what is needed.

Sure! Let's do that. When we start working on it, we use this PR as a starting point to get some ideas (if needed)

2025-03-14 07:14 UTC, forman commented
> @b-yogesh I close this PR, I create an issue instead that specifies what is needed.

See #111

2025-03-14 07:14 UTC, closed without merging