Add `Table` component
bcdev/chartlets pull request #92
Opened 2024-12-27 14:02 UTC by b-yogesh

Addresses #41

2025-02-24 15:33 UTC, forman requested changes
Overall very good, but I don't like the way how row data is specified.

2025-02-24 15:33 UTC, forman commented on chartlets.py/chartlets/components/table.py
> +
I suggest simplifying this for users. I have a problem with the redundancy introduced here and the being forced to provide values for all properties as there are no specified defaults. My suggestion

- allow passing a list of lists as row data instead being forced to have dicts with data properties
- it is unlikely that users need to format specific row cells individually, for columns this is quite common 
- please document the default values

2025-02-26 09:03 UTC, b-yogesh commented on chartlets.py/demo/my_extension/__init__.py
> +from .my_panel_6 import panel as my_panel_6
Yes, created an issue here: https://github.com/bcdev/chartlets/issues/105

2025-02-26 09:04 UTC, b-yogesh commented on chartlets.py/chartlets/components/table.py
> +
Have updated the component based on your comments.

2025-02-26 10:38 UTC, forman approved these changes
Thanks, looks good! Tiny suggestion

2025-02-26 10:38 UTC, forman commented on chartlets.py/chartlets/components/table.py
> +TableRow = list[list[str | int | float | bool | None]]
```suggestion
TableRow: TypeAlias = list[list[str | int | float | bool | None]]
```

2025-02-26 10:38 UTC, forman commented on chartlets.py/chartlets/components/table.py
> +from dataclasses import dataclass
Add copyright header

2025-02-26 10:38 UTC, forman commented on chartlets.py/chartlets/components/table.py
> +from dataclasses import dataclass
Wait, all cp headers are missing. We fix that for whole Chartlets in another PR.

2025-02-26 10:49 UTC, b-yogesh commented on chartlets.py/chartlets/components/table.py
> +from dataclasses import dataclass
https://github.com/bcdev/chartlets/issues/106

2025-02-26 10:53 UTC, merged